# Flask Dockerfile

FROM rockit-backend-beta-base
    
COPY backend backend

RUN rm backend/.env || true

RUN chown -R 1000:1000 /backend
RUN mkdir /.spotdl
RUN chown -R 1000:1000 /.spotdl

# USER 1000:1000

CMD ["fastapi", "run", "backend/main.py"]

