# Flask Dockerfile
# FROM python:3.10-slim

FROM rockit-nextjs-fastapi-base
    
COPY backend backend

RUN rm backend/.env || true

RUN chown -R 1000:1000 /backend
RUN mkdir /.spotdl
RUN chown -R 1000:1000 /.spotdl

# USER 1000:1000

CMD ["fastapi", "run", "backend/main.py"]

