# Dockerfile.worker
FROM node:20.18.3-bullseye 

WORKDIR /app

RUN apt-get update && apt-get install -y python3 build-essential

# Set Python for node-gyp
# RUN npm config set python "/usr/bin/python3"
RUN export python3=/usr/bin/python3

# Install dependencies
COPY package.json pnpm-lock.yaml ./
RUN npm install pnpm -g

# Copy application code
COPY . .

RUN rm .env || true

RUN chown -R 1000:1000 /app

RUN mkdir /app/database

RUN pnpm install

CMD ["npx", "tsx", "src/worker.ts"]
