export enum EMediaContextAction {
    Play = "play",
    AddToPlaylist = "addToPlaylist",
    Navigate = "navigate",
    AddToLibrary = "addToLibrary",
    RemoveFromLibrary = "removeFromLibrary",
    PlayList = "playList",
    AddToQueueTop = "addToQueueTop",
    AddQueueRandom = "addQueueRandom",
    AddToQueueBottom = "addToQueueBottom",
    DownloadZip = "downloadZip",
    RetryDownload = "retryDownload",
    Download = "download",
    RemoveFromQueue = "removeFromQueue",
    AddSongToQueueTop = "addSongToQueueTop",
    AddMediaQueueRandom = "addSongQueueRandom",
    AddMediaToQueueBottom = "addSongToQueueBottom",
    RemoveFromPlaylist = "removeFromPlaylist",
    Delete = "delete",
    Redownload = "redownload",
    EditMetadata = "editMetadata",
    DownloadSearchResult = "downloadSearchResult",
    DownloadSearchResultAndAddToLibrary = "downloadSearchResultAndAddToLibrary",
    DownloadSearchResultAndPlay = "downloadSearchResultAndPlay",
    AddToPlaylistAndDownload = "addToPlaylistAndDownload",
    SaveOffline = "saveOffline",
}
