import type { Metadata } from "next";
import "@/styles/default.css";
import Footer from "@/components/Footer/Footer";
import { headers } from "next/headers";
import Navigation from "@/components/Navigation";
import AddSessionProvider from "@/components/AddSessionProvider";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
    title: "RockIt",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const headerList = await headers();
    const pathname = headerList.get("x-current-path");

    if (pathname == "/login") {
        return (
            <html lang="en">
                <head>
                    <link
                        rel="icon"
                        type="image/svg+xml"
                        href="/rockit-logo.ico"
                    />
                    <link rel="manifest" href="/manifest.json" />
                </head>
                <body className="bg-black">
                    <div className="fixed top-0 left-0 right-0 bottom-0 bg-[#0b0b0b]">
                        {children}
                    </div>
                </body>
            </html>
        );
    }

    return (
        <html lang="en">
            <head>
                <link rel="icon" type="image/svg+xml" href="/rockit-logo.ico" />
                <link rel="manifest" href="/manifest.json" />
            </head>
            <body className="bg-black">
                <div className="fixed top-0 left-12 right-0 bottom-0 bg-[#0b0b0b]">
                    {children}
                </div>

                <div className="fixed left-12 right-0 top-0 h-24 w-auto">
                    <Header></Header>
                </div>
                <div className="fixed left-0 right-0 bottom-0 h-24 ">
                    <Footer></Footer>
                </div>
                <div className="fixed top-0 left-0 bottom-24">
                    <AddSessionProvider>
                        <Navigation></Navigation>
                    </AddSessionProvider>
                </div>
            </body>
        </html>
    );
}
