import type { Vocabulary } from "./types/vocabulary";

export const DEFAULT_VOCABULARY: Vocabulary = {
    ADD_LIST_RANDOMLY: "Add randomly",
    ADD_LIST_TO_BOTTOM: "Add to bottom",
    ADD_LIST_TO_QUEUE: "Add to queue",
    ADD_SONG_TO_PLAYLIST: "Add to playlist",
    ADD_SONG_TO_QUEUE: "Add to queue",
    ADD_TO_LIBRARY: "Add to library",
    ADD_TO_LIKED: "Add to liked",
    ADD_TO_QUEUE: "Add to queue",
    ALBUM: "Album",
    ALBUMS: "Albums",
    ALBUMS_SINGLES: "Albums & Singles",
    ALL: "All",
    APRIL: "April",
    ARTIST: "Artist",
    ARTISTS: "Artists",
    AUGUST: "August",
    AVERAGE_MINUTES_PER_SONG: "Avg min/song",
    BY: "By",
    CANCEL: "Cancel",
    CHANGE_PASSWORD: "Change password",
    CLEAR_DOWNLOADS: "Clear downloads",
    COMMUNITY_TOP: "Community Top",
    COPY_LIST_URL: "Copy list URL",
    COPY_SONG_URL: "Copy song URL",
    CREATE: "Create",
    CREATING: "Creating...",
    DATE_ADDED: "Date added",
    DECEMBER: "December",
    DEVICE_DOESNT_SUPPORT_SERVICE_WORKER:
        "Device doesn't support service workers",
    DISC: "Disc",
    DISPLAY_NAME: "Account",
    DOWNLOAD: "Download",
    DOWNLOAD_APP: "App",
    DOWNLOAD_INPUT_PLACEHOLDER: "Paste a Spotify or YouTube URL",
    DOWNLOAD_LIST_TO_DEVICE: "Download to device",
    DOWNLOAD_MEDIA_TO_DEVICE: "Download to device",
    DOWNLOAD_MP3: "Download MP3",
    DOWNLOAD_SONG_TO_DEVICE: "Download to device",
    DOWNLOAD_ZIP: "Download ZIP",
    DOWNLOADS: "Downloads",
    DURATION: "Duration",
    ENERGY: "Energy",
    ENTER_NEW_PLAYLIST_NAME: "Enter new playlist name",
    ERROR: "Error",
    ERROR_CREATING: "Error creating",
    ERROR_CREATING_PLAYLIST: "Error creating playlist",
    ERROR_ENTER_NAME: "Please enter a name",
    FEATURED_ALBUMS: "Featured albums",
    FEATURED_LISTS: "Featured lists",
    FEBRUARY: "February",
    FOCUS: "Focus",
    FRIENDS: "Friends",
    FRIENDS_LIST: "Friends list",
    FRIENDS_POINTS_DESCR: "Earn points by listening to music",
    FRIENDS_STATS: "Friends stats",
    GENERAL: "General",
    GENERAL_STATS: "General stats",
    GET_INFO: "Get info",
    GO_TO_ALBUM: "Go to album",
    GO_TO_ARTIST: "Go to artist",
    HIDDEN_GEMS: "Hidden Gems",
    HOME: "Home",
    JANUARY: "January",
    JULY: "July",
    JUNE: "June",
    LANGUAGE: "Language",
    LATEST_DOWNLOADS: "Latest downloads",
    LEVEL_ABBR: "Lv",
    LIBRARY: "Library",
    LIKE: "Like",
    LIKED_SONGS: "Liked songs",
    LOG_OUT: "Log out",
    LYRICS: "Lyrics",
    MARCH: "March",
    MAY: "May",
    MINUTES: "min",
    MINUTES_LISTEND: "Minutes listened",
    MINUTES_LISTENED_PER_DAY: "Minutes listened per day",
    MOOD_SONGS: "Mood songs",
    MORE_OPTIONS: "More options",
    MORE_SONGS_FROM: "More songs from",
    MOST_LISTENED: "Most listened",
    MOST_LISTENED_ALBUMS: "Most listened albums",
    MOST_LISTENED_ARTISTS: "Most listened artists",
    MOST_LISTENED_SONGS: "Most listened songs",
    NAME: "Name",
    NEW_PASSWORD: "New password",
    NEW_PLAYLIST: "New playlist",
    NEW_PLAYLIST_NAME: "New playlist name",
    NO_ALBUMS: "No albums yet",
    NO_DATA: "No data available",
    NO_LYRICS: "No lyrics available",
    NO_PLAYLISTS: "No playlists yet",
    NO_RESULTS: "No results found",
    NO_SERVICE_WORKER: "No service worker",
    NO_SONGS: "No songs yet",
    NO_STATE: "No state",
    NO_STATIONS: "No stations yet",
    NO_VIDEOS: "No videos yet",
    NOVEMBER: "November",
    OCTOBER: "October",
    OPEN_LIST: "Open list",
    OPEN_SONG: "Open song",
    PARTY: "Party",
    PAUSE_SONG: "Pause song",
    PENDING_REQUESTS: "Pending requests",
    PIN: "Pin",
    PINNED_LISTS: "Pinned lists",
    PLACEHOLDER_ALBUM: "Album name",
    PLACEHOLDER_ARTIST: "Artist name",
    PLACEHOLDER_PLAYLIST_NAME: "Playlist name",
    PLACEHOLDER_SONG: "Song name",
    PLAY_LIST: "Play list",
    PLAY_MEDIA: "Play",
    PLAY_NEXT: "Play next",
    PLAY_SONG: "Play song",
    PLAYLISTS: "Playlists",
    QUICK_SELECTIONS: "Quick Selections",
    RADIO: "Radio",
    RADIO_EMPTY1: "Search for a station",
    RADIO_EMPTY2: "to start listening",
    RADIO_SEARCH: "Search stations...",
    RADIO_STATIONS: "Radio Stations",
    RECENT_MIX: "Recent mix",
    RECENT_PLAYED: "Recently played",
    RECENTLY_PLAYED: "Recently Played",
    REGISTER: "Register",
    REGISTERED: "Registered",
    REGISTERING: "Registering...",
    RELATED_ARTISTS: "Related artists",
    RELAXED: "Relaxed",
    REMOVE_FROM_LIBRARY: "Remove from library",
    REMOVE_FROM_LIKED: "Remove from liked",
    REMOVE_FROM_PLAYLIST: "Remove from playlist",
    REMOVE_FROM_QUEUE: "Remove from queue",
    REPEAT_PASSWORD: "Repeat password",
    SEARCH: "Search",
    SEARCH_BAR: "Search music...",
    SEARCH_EMPTY1: "Search for songs, albums,",
    SEARCH_EMPTY2: "artists or playlists",
    SEARCH_LIBRARY: "Search in library...",
    SEARCH_USERS: "Search users",
    SEND_SONG: "Send song",
    SEPTEMBER: "September",
    SETTINGS: "Settings",
    SHARE_SONG: "Share song",
    SHARED_2_YOU: "Shared with you",
    SHARED_FROM: "Shared from",
    SHOWING_DATA: "Showing data",
    SONG: "Song",
    SONGS: "Songs",
    SONGS_FOR_YOU: "Songs for you",
    SONGS_FROM: "Songs from",
    SONGS_LISTENED: "Songs listened",
    STATISTICS: "Statistics",
    STATS: "Stats",
    STOP: "Stop",
    TO: "to",
    TOP_ALBUMS: "Top albums",
    TOP_SONGS: "Top songs",
    UNPIN: "Unpin",
    UNREGISTER: "Unregister",
    UNREGISTERED: "Unregistered",
    UNREGISTERING: "Unregistering...",
    UPDATE: "Update",
    UPDATING: "Updating...",
    UPLOAD: "Upload",
    USER: "User",
    USER_SETTINGS: "User Settings",
    USER_STATS: "User stats",
    USERS_FRIENDS: "Users friends",
    USERS_LIST: "Users list",
    VIDEOS: "Videos",
    YOU_MIGHT_LIKE: "You might like",
    YOUR: "Your",
    YOUR_ALBUMS_PLAYLISTS: "Your albums & playlists",
    YT_VIDEOS: "YouTube Videos",
    SAVING: "Saving...",
};
